FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    git \
    libpq-dev \
    postgresql-client \
    apt-get clean \
    docker.io

USER jenkins